Repository visheshrwl/Uber-like, pull requests merged in 2024-10, with the labels that each got.

#16 Update TripResolver.ts
  backend/src/resolvers/TripResolver.ts
Labels: hacktoberfest-accepted

#15 Update Ride.ts
  backend/src/entity/Ride.ts
Labels: hacktoberfest-accepted

#20 #Add Code_Of_Conduct.md
  Code_Of_Conduct.md
Labels: gssoc-ext, level-1

#18 Create health.ts
  backend/src/resolvers/health.ts
Labels: gssoc-ext, level-1

#17 Create healthCheck.ts
  backend/src/entity/healthCheck.ts
Labels: gssoc-ext, hacktoberfest-accepted, level-1

#23 Update service.yml
  kubernetes/service.yml
Labels: gssoc-ext, hacktoberfest-accepted, level-2

#22 Update ingress.yml
  kubernetes/ingress.yml
Labels: gssoc-ext, hacktoberfest-accepted, level-2

#21 Update deployment.yml
  kubernetes/deployment.yml
Labels: hacktoberfest-accepted

#30 Update ingress.yml
  kubernetes/ingress.yml
Labels: gssoc-ext, hacktoberfest-accepted, level-2

#25 Create auto-comment-issue.yml
  .github/workflows/auto-comment-issue.yml
Labels: gssoc-ext, hacktoberfest-accepted, level-1

#32 "Enhance README for Improved User Engagement"
  Readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level-1

#33 improved backend security
  .env.example
  backend/src/constants.ts
  backend/src/data-source.ts
  backend/src/entity/Delivery.ts
  backend/src/entity/RefreshTokens.ts
  backend/src/entity/User.ts
  backend/src/entity/healthCheck.ts
  backend/src/index.ts
  backend/src/resolvers/TripResolver.ts
  backend/src/resolvers/UserResolver.ts
  package-lock.json
  package.json
Labels: hacktoberfest-accepted

#35 LICENSE FILE ADDED
  LICENSE
  Readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level-1

#55 updated the correct command for cloning the fork .
  Readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#59 The command for creating a new branch is corrected
  Readme.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#61 Add Rider dashboard
  .env.example
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/component/Dashboard.css
  frontend/src/component/Dashboard.jsx
  frontend/src/component/Map.jsx
  frontend/src/component/RideForm.jsx
  frontend/src/component/RideStatus.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#70 added chatbot
  frontend/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#67 [Documentation] : Enhancement Of Contributing.md
  Contribution.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#73 added driver map
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/component/Drivermap.jsx
  frontend/src/component/Map.css
  frontend/src/component/footer.css
  frontend/src/component/header.css
  frontend/src/component/header.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#66 added multilanguage support
  frontend/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#75 Added FareEstimation Feature and Integrated it with Backend
  frontend/src/App.jsx
  frontend/src/component/FareEstimate.css
  frontend/src/component/FareEstimate.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#78 modified faq section
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/FaqSection.css
  frontend/src/component/faqsection.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1, frontend

#82 Updated the readme file
  Readme.md
  assets/GSSoC-Ext.png
  assets/hacktoberfest.png
Labels: gssoc-ext, hacktoberfest-accepted, level1

#81 add driver tracking
  backend/src/index.ts
  backend/src/services/websocketService.ts
  frontend/.env.example
  frontend/src/App.jsx
  frontend/src/component/DriverMap.jsx
  frontend/src/component/RideTracking.jsx
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, level2

#79 fixed the bug and added header file in both of the area needed
  frontend/index.html
  frontend/src/component/RideForm.jsx
  frontend/src/component/RideStatus.jsx
  frontend/src/component/faqsection.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#85 Implement Issue Reminder Workflow🚀
  .github/workflows/issue-reminder.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#86 Add GitHub Workflows for Greetings, Auto-Labeling, and PR Merge Notifications
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2
